bk

diff --git a/src/container b/src/container
--- a/src/container
+++ b/src/container
@@ -72,17 +72,20 @@ export CAT8="${COLOR}  .^.   .^.
 |ﾙﾘﾘ >   )ﾘ
 ﾉノ㇏ ひ ﾉ|ﾉ
       ⠁⠁"
-function error(){
+# Show error message and exit.
+function error() {
   echo "\033[31m$@" >&2
   exit 1
 }
 # Load configs&&check the environment.
 function _init() {
   if [[ ! -e /data/data/com.termux/files/usr/etc/container/global.conf ]]; then
-    error "\033[31mCould not find global config file !"
+    error "\033[31mCould not find global config file!"
   fi
   source /data/data/com.termux/files/usr/etc/container/global.conf
-  
+  if ! command -v capsh unshare chroot proot ruri; then
+    error "Missing dependencies!"
+  fi
 }
 # i18n
 function po_getmsg() {
@@ -185,6 +188,7 @@ function show_info() {
   echo -e "[] $(po_getmsg "Platform Codename")     : $(getprop ro.board.platform)"
   echo -e "[] $(po_getmsg "Cpus")                  : $(lscpu | grep CPU\(s\)\: | awk '{print $2}')"
   echo -e "[] $(po_getmsg "Total Memory")          : $(free -g --si | grep "Mem" | awk {'print $2'})GB"
+  #XXX
   _temp=$(cat /sys/class/thermal/thermal_zone0/temp)
   temp=$(echo $_temp | cut -c 1-2)
   temp+=".$(echo $_temp | cut -c 3)"
